version: '3.6'

services:

  farming:
    image: iforcomenergysolution/farming:1.0
    restart: always
    environment:
      InputType: "file"
      URI: "ContainerSetting.json"
      WaitTime: 10000
      ContainerRemove: "False"
      Ignore: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
